pipeline:
  name: Build azure-deployment
  identifier: Build_Abhijit_IBM_azure_deployment_1709180585186
  projectIdentifier: Azure_Deployment
  orgIdentifier: default
  stages:
    - stage:
        name: Provision Resources
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Terraform Plan
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      cd terraform
                      terraform --version
                      terraform plan
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: Abhijit-IBM/azure-deployment
        build: <+input>
