pipeline:
  name: Build azure-deployment
  identifier: Build_Abhijit_IBM_azure_deployment_1709180585186
  projectIdentifier: Azure_Deployment
  orgIdentifier: default
  stages:
    - stage:
        name: Provision Resources
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Terraform Init
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:latest
                    shell: Sh
                    command: |-
                      cd terraform
                      terraform --version
                      terraform init
                    imagePullPolicy: IfNotPresent
                    runAsUser: "0"
              - step:
                  type: Run
                  name: Azure Login
                  identifier: Azure_Login
                  spec:
                    shell: Bash
                    command: az login
              - step:
                  type: Run
                  name: Terraform Plan
                  identifier: Terraform_Plan
                  spec:
                    shell: Bash
                    command: |-
                      cd terraform
                      terraform plan
                    envVariables:
                      VM_PASS: <+secrets.getValue("azurelogin")>
              - step:
                  type: Run
                  name: Terraform Apply
                  identifier: Terraform_Apply
                  spec:
                    shell: Sh
                    command: terraform apply -auto-approve
                    envVariables:
                      VM_PASS: <+secrets.getValue("azurelogin")>
              - step:
                  type: Run
                  name: Terraform Destroy
                  identifier: Terraform_Destroy
                  spec:
                    shell: Sh
                    command: terraform destroy -auto-approve
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
        description: ""
        delegateSelectors:
          - docker-delegate
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: Abhijit-IBM/azure-deployment
        build: <+input>
